spring.application.name=middleware
spring.data.mongodb.uri=mongodb+srv://user1:Admin1@m0.hwquuaq.mongodb.net/tvmaze_db?appName=M0
#Habilitar la creaci\u00f3n automatica de indices
spring.data.mongodb.auto-index-creation=true
